package generics;

/**
 * Create by 163 on 2018/11/28
 */
public enum Watercolor {
    ZINC,LEMON_YELLOW,MEDIUM_YELLOW,DEEP_YELLOW,ORANGE,
    BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,CERULEAN_BLUE_HUE,
    PHTHALO_BLUE,ULTRAMARINE,COBALT_BLUE_HUE,PERMANENT_GREEN,VIRIDIAN_HUE,
    SAP_GREEN,YELLOW_OCHRE,
}
